name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalação das dependências do projeto
        run: npm install

      - name: Execução dos testes
        run: npx mocha testes/trabalho-final.js
