name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do projeto para a máquina de execução
        uses: actions/checkout@v4

      - name: Configuração do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalação das dependências do projeto
        run: npm install

      - name: Execução dos testes unitários
        run: npm test
      
      - name: Publica o resultado dos testes
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Mocha Unit Tests
          path: test-results.xml
          reporter: jest-junit
          fail-on-error: false
